# Generated by Django 3.0.3 on 2020-04-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=30)),
                ('time', models.TimeField(default='00:00 AM')),
                ('date', models.DateField(default='2019-6-14')),
                ('start_position', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('max_members', models.PositiveIntegerField(default=4, help_text='maximum number of members includes you as well.')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bookings.Booking')),
            ],
        ),
    ]
