# Generated by Django 3.0.3 on 2020-04-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200426_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='cab_timing',
            field=models.CharField(max_length=90),
        ),
    ]
