# Generated by Django 3.0.3 on 2020-04-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20200429_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
