# Generated by Django 3.0.3 on 2020-04-29 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20200429_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_members', to='bookings.Booking'),
        ),
    ]
