# Generated by Django 3.0.3 on 2020-04-29 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20200429_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
