# Generated by Django 3.0.3 on 2020-04-29 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_chat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
