# Generated by Django 3.0.3 on 2020-04-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(choices=[('both boys and girls', 'both boys and girls'), ('girls only', 'girls only'), ('boys lonly', 'boys only')], default='both', max_length=20),
        ),
    ]
