# Generated by Django 3.0.3 on 2020-05-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_chat_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'time']},
        ),
    ]
