# Generated by Django 3.0.3 on 2020-05-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20200501_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
