# Generated by Django 3.0.3 on 2020-05-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_booking_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(choices=[('all', 'all'), ('girls only', 'girls only'), ('boys only', 'boys only')], default='both', max_length=20),
        ),
    ]
